### ISSUE TITLE
performance measurement probleme beheben

### ISSUE THREAD

**Issue by alkor200** [LID-DS/LID-DS#205]
Bitte die gesammelten Performance Measurement Bugs aus den Kommentaren fixen

**Comment by boneymoy88** [comment]
Traceback (most recent call last):
  File "ids_lstm_main.py", line 49, in <module>
    ids.do_detection()
  File "/home/tk/Documents/LID-DS/algorithms/ids.py", line 126, in do_detection
    def get_performance(self):
ZeroDivisionError: float division by zero
