### ISSUE TITLE
fix Json String parse Bug

### ISSUE THREAD

**Issue by alkor200** [LID-DS/LID-DS#420]
Traceback (most recent call last):
  File "ids_lstm_main.py", line 153, in <module>
    results['config'] = ids.get_config_tree_links()
  File "/home/tk/Documents/WHK/LID-DS/algorithms/ids.py", line 82, in get_config_tree_links
    json_loaded = json.loads(json_string)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 353 (char 352)

**Comment by alkor200** [comment]
neues ToDo: Problem tritt auch bei Enums im String auf
